apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: darkmode-demo
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/syedazeez337/argo-darkmode-demo.git
        revision: main
        directories:
          - path: darkmode
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/syedazeez337/argo-darkmode-demo.git
        targetRevision: main
        path: darkmode
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
